
import type {Metadata} from 'next';
import './globals.css';
import { Analytics } from '@vercel/analytics/next';
import {Toaster} from '@/components/ui/toaster';
import { ClerkProvider } from "@clerk/nextjs";
import { TooltipProvider } from "@/components/ui/tooltip";
import { I18nProvider } from "@/components/providers/i18n-provider";

export const metadata: Metadata = {
  title: 'Sacred Library | Divine Wisdom & Reflection',
  description: 'Your personal sanctuary for scripture, devotionals, and spiritual growth.',
  keywords: [
    "la biblia",
    "que es la biblia",
    "dios",
    "versículo",
    "versículo biblia",
    "biblia catolica",
    "versículo de la biblia",
    "reina valera",
    "biblia reina valera",
    "versiculo biblia",
    "salmo",
    "versiculo de la biblia",
    "versiculos de la biblia",
    "biblia católica",
    "versículos de la biblia",
    "la biblia reina valera",
    "mateo",
    "biblia reina valera 1960",
    "libros de la biblia",
    "biblia todo",
    "la biblia catolica",
    "reina valera 1960",
    "biblia pdf",
    "en qué parte de la biblia dice",
    "biblia latinoamericana",
    "santa biblia",
    "biblia cristiana",
    "lucas",
    "biblia para niños",
    "salmos",
    "proverbios",
    "la biblia pdf",
    "corintios",
    "apocalipsis biblia",
    "apocalipsis",
    "romanos",
    "la biblia reina valera 1960",
    "salmo 91",
    "la santa biblia",
    "mujeres de la biblia",
    "biblia de estudio",
    "isaias",
    "los libros de la biblia",
    "hechos",
    "genesis",
    "salmos de la biblia",
    "job",
    "job biblia",
    "frases de la biblia",
    "hebreos",
    "bible youversion",
    "youversion bible",
    "bible app",
    "youversion bible app",
    "biblia app",
    "youversion app",
    "app biblia",
    "the bible",
    "in the bible",
    "bible verse",
    "bible verses",
    "jesus",
    "study bible",
    "bible study",
    "kjv bible",
    "gateway bible",
    "bible gateway",
    "catholic bible",
    "matthew",
    "holy bible",
    "bible app",
    "bible online",
    "online bible",
    "king james bible",
    "books of the bible",
    "psalm",
    "bible quotes",
    "niv bible",
    "hebrew bible",
    "proverbs",
    "the holy bible",
    "verse of the day",
    "esv bible",
    "bible verse of the day",
    "bible scriptures",
    "genesis bible",
    "genesis",
    "romans",
    "luke",
    "isaiah",
    "corinthians",
    "bible in a year",
    "revelation",
    "bible project",
    "bible hub",
    "psalms",
    "audio bible",
    "who wrote the bible",
    "women of the bible",
    "acts",
    "blue letter bible",
    "ethiopian bible",
    "jewish bible",
    "best bible verses",
    "nlt bible",
    "jeremiah",
    "ephesians",
    "the faithful women of the bible",
    "bible in 365.com",
    "pulp fiction bible verse",
    "ethiopian bible",
    "ethiopian bible in english",
    "women of the bible",
    "the bible series",
    "bible verse for today",
    "bible app",
    "best bible verses",
    "enoch in the bible",
    "youversion bible app",
    "scofield bible",
    "bible in a year",
    "what does the bible say about cremation",
    "1 john",
    "fasting in the bible",
    "cute bible verses",
    "ezekiel",
    "today's bible verse",
    "the bible project",
    "acts",
    "jesus",
    "pink bible",
    "matthew",
    "galatians",
    "how many chapters are in the bible",
    "short bible verses",
    "what does the bible say about homosexuality",
    "2 corinthians",
    "jewish bible",
    "wormwood bible",
    "deuteronomy",
    "youversion bible",
    "in the bible",
    "esther in the bible",
    "esv study bible",
    "1 peter",
    "bible versus",
    "jeremiah",
    "audio bible",
    "colossians",
    "catholic bible",
    "online bible",
    "bible online",
    "corinthians",
    "good bible verses",
    "bible verses of the day",
    "niv bible",
    "bible belt",
    "god is",
    "is god is",
    "bible",
    "god of war",
    "what a god",
    "jesus",
    "who is god",
    "greek god",
    "church of god",
    "fear of god",
    "is jesus god",
    "god is good",
    "god father",
    "essentials",
    "fear of god essentials",
    "essentials fear of god",
    "god of war ragnarok",
    "oh my god",
    "trust in god",
    "bible verses",
    "god is love",
    "city of god",
    "goodness of god",
    "sun god",
    "the god father",
    "lamb of god",
    "assembly of god",
    "psalm",
    "armor of god",
    "names of god",
    "is god real",
    "genesis",
    "romans",
    "god speed",
    "i thank god",
    "zeus",
    "zeus god",
    "essentials hoodie",
    "tower of god",
    "rap god",
    "god only knows",
    "fear of god essentials hoodie",
    "essentials fear of god hoodie",
    "essentials hoodie fear of god",
    "their eyes were watching god",
    "i trust in god",
    "isaiah",
    "apollo",
    "god bless america",
    "kratos",
    "god of war sons of sparta",
    "quad god",
    "let god sort em out",
    "phil wickham what an awesome god",
    "stop in the name of god",
    "god don't play about me",
    "god of war tv show",
    "drops of god season 2",
    "what a god chords",
    "stove god cooks",
    "our god is an awesome god",
    "what a god lyrics",
    "god knows where i am",
    "god speed",
    "i trust in god",
    "god of war 2018",
    "god of war 1",
    "ugly god",
    "our god is an awesome god lyrics",
    "i trust in god lyrics",
    "god of war 3",
    "god of war 2",
    "drops of god",
    "genesis",
    "is jesus god",
    "city of god movie",
    "kratos",
    "what a god",
    "1 peter",
    "god of malice",
    "exodus",
    "lamb of god tour",
    "lamb of god",
    "jeremiah",
    "god only knows",
    "is god real",
    "jesus",
    "isaiah",
    "god is good",
    "1 corinthians",
    "ephesians",
    "1 john",
    "trust in god lyrics",
    "god complex",
    "2 corinthians",
    "hebrews",
    "psalm",
    "children of god cult",
    "god is",
    "city of god",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Alegreya:wght@400;700&family=PT+Sans:wght@400;700&display=swap" rel="stylesheet" />
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('theme');var p=window.matchMedia('(prefers-color-scheme: dark)').matches;var d=t==='dark'||(!t&&p);var r=document.documentElement;if(d){r.classList.add('dark');}else{r.classList.remove('dark');}r.style.colorScheme=d?'dark':'light';}catch(e){}})();`,
          }}
        />
      </head>
      <body className="font-body antialiased selection:bg-blue-600/20" suppressHydrationWarning>
        <ClerkProvider>
          <I18nProvider>
            <TooltipProvider>
              {children}
              <Toaster />
              <Analytics />
            </TooltipProvider>
          </I18nProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
